version: '3'
x-airflow-common:
  &airflow-common
  image: ghcr.io/economiagovbr/ro-dou-jobs:latest
  user: "1000"
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__ENABLE_XCOM_PICKLING: 'true'
    AIRFLOW__CORE__FERNET_KEY: 'znEgRtj3Rip3uFm8DQ_MB5a4UiYtI0DWXnfI0fEv6Bo='
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__PARALLELISM: 2
    AIRFLOW__CORE__DEFAULT_TIMEZONE: 'America/Sao_Paulo'
    AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE: 'America/Sao_Paulo'
    AIRFLOW__EMAIL__DEFAULT_EMAIL_ON_RETRY: 'false'
    AIRFLOW__EMAIL__DEFAULT_EMAIL_ON_FAILURE: 'false'
    AIRFLOW__WEBSERVER__SECRET_KEY: '42'
    AIRFLOW__WEBSERVER__WORKERS: 1

    _AIRFLOW_DB_UPGRADE: 'true'
    _AIRFLOW_WWW_USER_CREATE: 'true'
    _AIRFLOW_WWW_USER_USERNAME: airflow
    _AIRFLOW_WWW_USER_PASSWORD: airflow

    # AIRFLOW__SMTP__SMTP_HOST:
    # AIRFLOW__SMTP__SMTP_STARTTLS:
    # AIRFLOW__SMTP__SMTP_SSL:
    # AIRFLOW__SMTP__SMTP_USER:
    # AIRFLOW__SMTP__SMTP_PASSWORD:
    # AIRFLOW__SMTP__SMTP_PORT:
    # AIRFLOW__SMTP__SMTP_MAIL_FROM:

    AIRFLOW_CONN_EXAMPLE_DATABASE_CONN: postgresql://airflow:airflow@postgres:5432/airflow
  volumes:
    # Logs
    - ../airflow-mnt/logs:/opt/airflow/logs
  depends_on:
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - ../airflow-mnt/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: always

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    command: webserver
    ports:
      - 80:8080
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:80/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: scheduler
    restart: always
